"supplier_id","supplier_name","manufacturer",
"1","Suy Sing","PPMC",
"2","World Power Zone","Del Monte Phils. Inc.",
"3","PMFTC Inc.","PGG",
"4","DDI","Unilever",
"5","RGPI","Proctor & Gamble",
"6","Triple J","NutriAsia",
"7","PGG","URC",
"8","RZM","Republic Biscuit Corp.",
"9","Supplier 1","Manu 1",
"10","test","",
"25","MSGcorp","",
"27","Samsung","",
"29","tester","",
"30","alert","",
